REM MUSICBRAINZ_ID "pNtImOkdBm9RMBIalzx0w9cfsYY-"
REM DISCID "E20DFE0E"
REM MEDIA "HDCD"
REM COMMENT "cyanrip 0.9.4-rc2+platterpus.11"
TITLE "Unknown disc (PNTI)"
FILE "01.pcm" WAVE
  TRACK 01 AUDIO
    TITLE "Unknown track"
    INDEX 01 00:00:00
