#!/usr/bin/env python3
#
# This file is part of cyanrip.
#
# cyanrip is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# cyanrip is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with cyanrip; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

"""Compile the handshake state into the binary, so a rip can report it.

The release rule lives in docs/handshake/ and is enforced at release time by
tools/release-gate.py. That is one step too late for the question a consumer
actually has, which is asked months afterwards while looking at a logfile:

    "was this rip produced by a pair of builds that had agreed with each other?"

Nothing in a log could answer that before. The version banner says which cyanrip
wrote it and nothing says whether that cyanrip was a released, mutually-verified
build or a mid-round working tree. Those are different provenance and an
archival record must not conflate them.

So the round state is compiled in from the same files the release gate reads,
and cyanrip prints it. A build from a tree with an open round says so, in every
logfile it writes, permanently.

Regenerated by meson whenever a round file changes, so it cannot go stale
against the documents it summarises -- a hand-maintained copy of this would be a
claim about the record rather than a derivation from it.
"""

import argparse
import importlib.util
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SPEC = importlib.util.spec_from_file_location(
    "release_gate", HERE / "release-gate.py")
rg = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(rg)


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _known_dirty():
    """True only when git is available AND reports uncommitted changes.

    Three states, deliberately not two. A tree git says is dirty is not a
    release. A tree git says is clean may be. A tree we cannot ask -- an
    unpacked tarball, no .git -- is UNKNOWN, and unknown must not refuse here.

    That last clause is the whole reason this function replaced a stricter one.
    Platterpus installs from `https://github.com/.../archive/<sha>.tar.gz`; it
    is the only install path the manifest offers. A check that demands a clean
    git tree therefore refuses the exact artifact a user installs, which would
    have reintroduced unreachability through the distribution channel after
    round 10 removed it from the condition. Measured against the manifest's own
    `install` field, not assumed.

    The build-time declaration is what carries the claim (see main()); this only
    withdraws it where the tree is visibly modified.
    """
    try:
        return bool(subprocess.run(["git", "status", "--porcelain"], cwd=ROOT,
                                   capture_output=True, text=True,
                                   check=True).stdout.strip())
    except Exception:
        return False


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("output", nargs="?", help="header to write (default stdout)")
    # Round 10 §J1(b), agreed with Platterpus in lap 2. DEFAULT FALSE, and only
    # the release path passes it -- their one condition on accepting (b), and
    # the right one: the failure mode of a mis-set flag is a release that
    # UNDER-claims, never a working tree that OVER-claims. An assertion that
    # lies permissively lands in somebody's archival record forever; one that
    # lies in the refusing direction costs a line of prose.
    ap.add_argument("--declare-released", action="store_true",
                    help="assert at build time that this build is a published "
                         "release. Recorded as declared and explicitly not "
                         "verified -- the `Consumer:` idiom. Never set by "
                         "default; see docs/RELEASING.md.")
    args = ap.parse_args()

    rounds = rg.load_rounds()
    ok, _ = rg.check(rounds) if rounds else (False, ["no rounds"])
    latest = rounds[-1] if rounds else None

    if latest is None:
        # An empty record is not agreement. Say unknown rather than pretend.
        state = "unknown (no handshake record found)"
        released = 0
        peer = "unknown"
    else:
        lap = f" lap {latest.lap}" if latest.lap is not None else ""
        verdict = latest.verdict or "no verdict declared"
        if ok:
            state = f"round {latest.number}{lap} closed, verdict {verdict}"
            # A CLOSED ROUND IS NOT A RELEASED BUILD -- still true, still the
            # reason this is not just `ok`. At the moment round 8 closed on
            # ddf7ac3 the tree was 33 commits past it, carrying ten unreviewed
            # fixes, and `released = ok` alone had every log it wrote read as
            # jointly verified.
            #
            # The fix for that was `_head_is(latest.our_pin)` -- require the
            # build to BE the approved pin -- and it was correct about the
            # defect and unsatisfiable as a remedy. `our_pin` is read from a lap
            # file INSIDE the tree being built, so setting the flag needed that
            # file to contain the abbreviated SHA of the commit containing it.
            # A lap can only ever name an ancestor. Round 10 lap 1 measured it
            # across all 15 ledger commits and the tip: 16 for 16, always 0.
            #
            # Round 10 §J1(b): the build DECLARES it, in the `Consumer:` idiom
            # -- recorded as declared, explicitly not verified. It is the one
            # thing a build genuinely knows that its own tree cannot, because
            # no artifact inside a commit can name that commit.
            #
            # Two derived preconditions still gate the declaration, so a
            # mis-set flag cannot claim just anything:
            #   * the record must be closed -- an open round is never a release,
            #     and this is the half that has always worked;
            #   * the tree must not be VISIBLY dirty (see _known_dirty).
            released = 1 if (args.declare_released and not _known_dirty()) else 0
        else:
            state = f"round {latest.number}{lap} OPEN, verdict {verdict}"
            released = 0
        peer = latest.app_version or latest.peer_version or "not recorded"

    body = f"""/* Generated by tools/gen-handshake-state.py. Do not edit.
 *
 * Derived from docs/handshake/, the same files tools/release-gate.py reads.
 * Regenerated by the build whenever one of them changes. */
#pragma once

#define HANDSHAKE_STATE     {c_string(state)}
#define HANDSHAKE_RELEASED  {released}
#define HANDSHAKE_PEER      {c_string(peer)}
"""

    if not args.output:
        sys.stdout.write(body)
        return 0

    # Written only when the content actually changes.
    #
    # This runs on every build (build_always_stale), because the header has to
    # notice a round file being *added*, not merely one it already knew about
    # changing. Neither a configure-time glob nor a depfile can do that: both
    # enumerate what existed last time, so a new lap file appears and the header
    # goes on describing the previous one. That happened here -- a binary
    # reported "lap 2" from a tree whose latest lap was 3, which is precisely the
    # staleness a generated header exists to prevent.
    #
    # Running every build is cheap; rewriting every build would not be, because
    # the timestamp alone would recompile everything that includes this. Hence
    # the comparison.
    out = pathlib.Path(args.output)
    if not out.exists() or out.read_text(encoding="utf-8") != body:
        out.write_text(body, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
