#!/usr/bin/env python3
"""Regenerate docs/golden-reference.log and .diagnostics.json.

Why this is a tool and not a paragraph
--------------------------------------
The golden reference is the artifact Platterpus checks its parser against, and
it has to be regenerated at every version bump because its banner carries the
version. Until now that was a hand-run command reconstructed from the previous
reference's own `Invoked as:` line, and the reconstruction has gone wrong twice
in ways that were invisible afterwards:

  * **beta.8 shipped a reference generated at beta.7.** The bump moved the
    version and nobody re-ran the rip, so the artifact described a build that
    was not the release.
  * **Round 5's reference silently lost coverage** because `-Z` and `-G` were
    dropped from the reconstructed command. Nothing failed: a reference
    generated with fewer flags is a perfectly valid log, just of a smaller
    program. `sc_reference()` now asserts those four `-Z` lines and the
    over-full-scale peak exist, which is a check that only exists because the
    coverage was lost once.

So the invocation lives here, in one place, under version control, rather than
being re-derived from an artifact each time. `CANONICAL` below IS the recipe.

Adding a flag here widens what the reference guards, which is a change
Platterpus can observe -- it is handshake material. Removing one narrows it
silently, which is the failure above. Neither is a drive-by edit.

The reference cannot be generated into the commit that contains it: a log
carries the build tag of the binary that wrote it, and that binary cannot be
built from a tree containing a file that names it. So the released artifact is
always "generated by X, committed at Y" and both must be stated -- see
CLAUDE.md, "a generated artifact needs two commits named".

Usage:
    ninja -C build && tools/gen-golden-reference.py
    tools/gen-golden-reference.py --check     # non-zero if it would change
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIX = ROOT / "tests" / "fixtures"
OUT_LOG = ROOT / "docs" / "golden-reference.log"
OUT_JSON = ROOT / "docs" / "golden-reference.diagnostics.json"

# The recipe. A 3-track image rip with the awkward options ON, deliberately:
# a reference generated from the convenient invocation guards less and says so
# nowhere. -Z 2 exercises the secure re-read surface, -G the true-peak path
# whose tag values exceed 1.0, -P 0 pins the paranoia cache-model size the
# suite also passes, and -j writes the diagnostics record beside the log.
CANONICAL = [
    "-d", "pregap.cue", "-N", "-A", "-Q", "-s", "0", "-o", "flac",
    "-Z", "2", "-G", "-F", "{track}", "-L", "reference", "-M", "sheet",
    "-P", "0", "-u", "platterpus/0.6.4b12",
    "-t", "1=isrc=AAAAA0000001",
    "-t", "2=isrc=BBBBB0000002",
    "-t", "3=isrc=CCCCC0000003",
]

# Fields that differ between any two runs of the same binary and carry no
# information about behaviour. --check ignores exactly these and nothing else,
# so a real difference cannot hide behind "it's just a timestamp".
VOLATILE = (
    (re.compile(r"^(Invoked as:\s+).*$", re.M), r"\1<normalised>"),
    # The build tag, ONLY in --check. It differs for every commit and during
    # development for every dirty tree, so leaving it strict would make --check
    # fail constantly for a reason that is not about content. Provenance is not
    # dropped -- sc_golden_reference_is_from_a_clean_build() asserts the
    # banner's VERSION equals meson.build's and that the tree was not dirty,
    # which is the claim that matters. This check is about the log's body.
    (re.compile(r"^(cyanrip \S+ \()[^)]*(\))"), r"\1<normalised>\2"),
    (re.compile(r"^(\s*creation_time:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(Ripping finished at ).*$", re.M), r"\1<normalised>"),
    # FUN512 is a checksum OVER the log, so it cannot match across runs once a
    # timestamp inside the log differs. Normalised here because the body it
    # covers is compared line by line anyway; the checksum itself is guarded by
    # the `verify_log` scenario, which round-trips it through --verify-log.
    (re.compile(r"^(Log FUN512: ).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(Total time taken:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(\s*Elapsed:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(\s*Extraction speed:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r'("(?:started_at|finished_at|elapsed_s)":\s*)[^,\n}]+'),
     r"\1<normalised>"),
)


def normalise(text):
    for pat, rep in VOLATILE:
        text = pat.sub(rep, text)
    return text


def generate(binary):
    """Run the canonical rip in a staged fixture dir; return (log, json)."""
    with tempfile.TemporaryDirectory() as td:
        work = Path(td)
        # libcdio's CDRDAO/bincue drivers pair sheets with their .bin by
        # basename and open the RELATIVE path, so the sheet must be ripped
        # from its own directory -- see CLAUDE.md's known-external-bugs list.
        for f in FIX.glob("*.cue"):
            shutil.copy(f, work)
        shutil.copy(FIX / "cdda.bin", work / "pregap.bin")

        out = work / "o"
        # -D and -j RELATIVE, run with cwd=work. The log prints the paths it
        # was handed, so an absolute -D rewrites every `File(s):` line and the
        # artifact stops being comparable to the committed one.
        argv = [str(binary)] + CANONICAL + ["-D", "o",
                                            "-j", "o/reference.diagnostics.json"]
        p = subprocess.run(argv, cwd=work, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT, timeout=300)
        log = out / "reference.log"
        js = out / "reference.diagnostics.json"
        if p.returncode != 0 or not log.exists() or not js.exists():
            sys.exit(f"the reference rip failed (exit {p.returncode}). It must "
                     "succeed or the artifact describes nothing:\n"
                     + p.stdout.decode(errors="replace")[-2000:])
        return log.read_text(), js.read_text()


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--binary", default=str(ROOT / "build" / "src" / "cyanrip"))
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed copy would change, "
                         "ignoring only wall-clock and invocation-path fields")
    args = ap.parse_args()

    if not Path(args.binary).exists():
        sys.exit(f"{args.binary}: not built. Run ninja -C build first.")

    log, js = generate(args.binary)

    # A reference from a dirty tree names a commit that does not describe it,
    # which is the whole defect sc_golden_reference_is_from_a_clean_build()
    # exists to catch. Refuse here too, where it is cheap.
    banner = log.splitlines()[0]
    if "-dirty" in banner:
        sys.exit(f"refusing to write a reference from a dirty build: {banner}\n"
                 "Commit, rebuild, and re-run.")

    if args.check:
        if not OUT_LOG.exists():
            sys.exit("docs/golden-reference.log is missing")
        old = normalise(OUT_LOG.read_text())
        new = normalise(log)
        if old != new:
            import difflib
            d = list(difflib.unified_diff(old.splitlines(), new.splitlines(),
                                          "committed", "regenerated", lineterm=""))
            sys.exit("the golden reference is stale:\n" + "\n".join(d[:60]))
        print("golden reference is up to date")
        return 0

    OUT_LOG.write_text(log)
    OUT_JSON.write_text(js)
    print(f"wrote {OUT_LOG.relative_to(ROOT)} and "
          f"{OUT_JSON.relative_to(ROOT)}\n  {banner}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
