#!/usr/bin/env python3
#
# This file is part of cyanrip.
#
# cyanrip is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# cyanrip is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with cyanrip; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

"""Compile the handshake state into the binary, so a rip can report it.

The release rule lives in docs/handshake/ and is enforced at release time by
tools/release-gate.py. That is one step too late for the question a consumer
actually has, which is asked months afterwards while looking at a logfile:

    "was this rip produced by a pair of builds that had agreed with each other?"

Nothing in a log could answer that before. The version banner says which cyanrip
wrote it and nothing says whether that cyanrip was a released, mutually-verified
build or a mid-round working tree. Those are different provenance and an
archival record must not conflate them.

So the round state is compiled in from the same files the release gate reads,
and cyanrip prints it. A build from a tree with an open round says so, in every
logfile it writes, permanently.

Regenerated by meson whenever a round file changes, so it cannot go stale
against the documents it summarises -- a hand-maintained copy of this would be a
claim about the record rather than a derivation from it.
"""

import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location(
    "release_gate", HERE / "release-gate.py")
rg = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(rg)


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("output", nargs="?", help="header to write (default stdout)")
    args = ap.parse_args()

    rounds = rg.load_rounds()
    ok, _ = rg.check(rounds) if rounds else (False, ["no rounds"])
    latest = rounds[-1] if rounds else None

    if latest is None:
        # An empty record is not agreement. Say unknown rather than pretend.
        state = "unknown (no handshake record found)"
        released = 0
        peer = "unknown"
    else:
        lap = f" lap {latest.lap}" if latest.lap is not None else ""
        verdict = latest.verdict or "no verdict declared"
        if ok:
            state = f"round {latest.number}{lap} closed, verdict {verdict}"
            released = 1
        else:
            state = f"round {latest.number}{lap} OPEN, verdict {verdict}"
            released = 0
        peer = latest.peer_version or "not recorded"

    body = f"""/* Generated by tools/gen-handshake-state.py. Do not edit.
 *
 * Derived from docs/handshake/, the same files tools/release-gate.py reads.
 * Regenerated by the build whenever one of them changes. */
#pragma once

#define HANDSHAKE_STATE     {c_string(state)}
#define HANDSHAKE_RELEASED  {released}
#define HANDSHAKE_PEER      {c_string(peer)}
"""

    if args.output:
        pathlib.Path(args.output).write_text(body, encoding="utf-8")
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
