#!/usr/bin/env python3
"""Regenerate docs/golden-reference.log and .diagnostics.json.

Why this is a tool and not a paragraph
--------------------------------------
The golden reference is the artifact Platterpus checks its parser against, and
it has to be regenerated at every version bump because its banner carries the
version. Until now that was a hand-run command reconstructed from the previous
reference's own `Invoked as:` line, and the reconstruction has gone wrong twice
in ways that were invisible afterwards:

  * **beta.8 shipped a reference generated at beta.7.** The bump moved the
    version and nobody re-ran the rip, so the artifact described a build that
    was not the release.
  * **Round 5's reference silently lost coverage** because `-Z` and `-G` were
    dropped from the reconstructed command. Nothing failed: a reference
    generated with fewer flags is a perfectly valid log, just of a smaller
    program. `sc_reference()` now asserts those four `-Z` lines and the
    over-full-scale peak exist, which is a check that only exists because the
    coverage was lost once.

So the invocation lives here, in one place, under version control, rather than
being re-derived from an artifact each time. `CANONICAL` below IS the recipe.

Adding a flag here widens what the reference guards, which is a change
Platterpus can observe -- it is handshake material. Removing one narrows it
silently, which is the failure above. Neither is a drive-by edit.

The reference cannot be generated into the commit that contains it: a log
carries the build tag of the binary that wrote it, and that binary cannot be
built from a tree containing a file that names it. So the released artifact is
always "generated by X, committed at Y" and both must be stated -- see
CLAUDE.md, "a generated artifact needs two commits named".

There is a SECOND artifact here, and it is not a golden reference. The
canonical rip completes, so it can never show what a rip stopped by a signal
looks like -- and after round 12 that is a shape Platterpus has to parse.
`--interrupted` writes docs/sample-interrupted.* : one real log and record from
a rip killed with SIGTERM mid-track. Where the signal lands is not
reproducible, so it is compared by LINE SHAPE and not byte for byte, and the
file says so in its own header rather than inviting a reader to diff it.

Usage:
    ninja -C build && tools/gen-golden-reference.py
    tools/gen-golden-reference.py --check                 # would it change?
    tools/gen-golden-reference.py --interrupted           # write the sample
    tools/gen-golden-reference.py --interrupted --check   # is it still current?
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIX = ROOT / "tests" / "fixtures"
OUT_LOG = ROOT / "docs" / "golden-reference.log"
OUT_JSON = ROOT / "docs" / "golden-reference.diagnostics.json"

# The recipe. A 3-track image rip with the awkward options ON, deliberately:
# a reference generated from the convenient invocation guards less and says so
# nowhere. -Z 2 exercises the secure re-read surface, -G the true-peak path
# whose tag values exceed 1.0, -P 0 pins the paranoia cache-model size the
# suite also passes, and -j writes the diagnostics record beside the log.
CANONICAL = [
    "-d", "pregap.cue", "-N", "-A", "-Q", "-s", "0", "-o", "flac",
    "-Z", "2", "-G", "-F", "{track}", "-L", "reference", "-M", "sheet",
    "-P", "0", "-u", "platterpus/0.6.4b12",
    "-t", "1=isrc=AAAAA0000001",
    "-t", "2=isrc=BBBBB0000002",
    "-t", "3=isrc=CCCCC0000003",
]

# Fields that differ between any two runs of the same binary and carry no
# information about behaviour. --check ignores exactly these and nothing else,
# so a real difference cannot hide behind "it's just a timestamp".
VOLATILE = (
    (re.compile(r"^(Invoked as:\s+).*$", re.M), r"\1<normalised>"),
    # The build tag, ONLY in --check. It differs for every commit and during
    # development for every dirty tree, so leaving it strict would make --check
    # fail constantly for a reason that is not about content. Provenance is not
    # dropped -- sc_golden_reference_is_from_a_clean_build() asserts the
    # banner's VERSION equals meson.build's and that the tree was not dirty,
    # which is the claim that matters. This check is about the log's body.
    (re.compile(r"^(cyanrip \S+ \()[^)]*(\))"), r"\1<normalised>\2"),
    (re.compile(r"^(\s*creation_time:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(Ripping finished at ).*$", re.M), r"\1<normalised>"),
    # FUN512 is a checksum OVER the log, so it cannot match across runs once a
    # timestamp inside the log differs. Normalised here because the body it
    # covers is compared line by line anyway; the checksum itself is guarded by
    # the `verify_log` scenario, which round-trips it through --verify-log.
    (re.compile(r"^(Log FUN512: ).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(Total time taken:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(\s*Elapsed:\s+).*$", re.M), r"\1<normalised>"),
    (re.compile(r"^(\s*Extraction speed:\s+).*$", re.M), r"\1<normalised>"),
    # The released/unreleased suffix and its qualifier line, ONLY in --check.
    #
    # These are a BUILD CONFIGURATION, not log content: the same commit built
    # with and without -Ddeclare_released=true produces both renderings, and the
    # reference is generated with the option at its default. Leaving them strict
    # made the shipping configuration fail its own suite -- measured, 2 of 41,
    # on the exact build our release manifest instructs the consumer to make.
    #
    # Same argument as the build tag above, and the same limit: this drops the
    # suffix from the BODY comparison only. It is not unguarded -- the
    # `handshake` scenario asserts the rendering directly against the
    # configuration the binary was actually built with, which is a stronger
    # check than diffing it here could be, because it knows which one to expect.
    #
    # The round/lap/verdict half of the line stays strict. That half is content.
    (re.compile(r"^(Handshake:\s+.*?) -- (?:NOT a )?released build$", re.M),
     r"\1 -- <build-declaration normalised>"),
    (re.compile(r"^\s*\(declared at build time, not verified by cyanrip\)\n",
                re.M), ""),
    (re.compile(r'("(?:started_at|finished_at|elapsed_s)":\s*)[^,\n}]+'),
     r"\1<normalised>"),
)


def normalise(text):
    for pat, rep in VOLATILE:
        text = pat.sub(rep, text)
    return text


def generate(binary):
    """Run the canonical rip in a staged fixture dir; return (log, json)."""
    with tempfile.TemporaryDirectory() as td:
        work = Path(td)
        # libcdio's CDRDAO/bincue drivers pair sheets with their .bin by
        # basename and open the RELATIVE path, so the sheet must be ripped
        # from its own directory -- see CLAUDE.md's known-external-bugs list.
        for f in FIX.glob("*.cue"):
            shutil.copy(f, work)
        shutil.copy(FIX / "cdda.bin", work / "pregap.bin")

        out = work / "o"
        # -D and -j RELATIVE, run with cwd=work. The log prints the paths it
        # was handed, so an absolute -D rewrites every `File(s):` line and the
        # artifact stops being comparable to the committed one.
        argv = [str(binary)] + CANONICAL + ["-D", "o",
                                            "-j", "o/reference.diagnostics.json"]
        p = subprocess.run(argv, cwd=work, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT, timeout=300)
        log = out / "reference.log"
        js = out / "reference.diagnostics.json"
        if p.returncode != 0 or not log.exists() or not js.exists():
            sys.exit(f"the reference rip failed (exit {p.returncode}). It must "
                     "succeed or the artifact describes nothing:\n"
                     + p.stdout.decode(errors="replace")[-2000:])
        return log.read_text(), js.read_text()


SAMPLE_HEADER = """\
=== THIS IS A SAMPLE, NOT A GOLDEN REFERENCE. DO NOT DIFF IT. ===

One real rip of tests/fixtures/pregap.cue, stopped with SIGTERM part way
through track 1, kept so a consumer writing a parser for an interrupted rip has
an artifact to open instead of a paragraph describing one. The canonical rip in
docs/golden-reference.log completes and therefore can never show this shape.

Where the signal lands is not reproducible, so how many frames were read, how
many track blocks exist and every timing differ between runs. Regenerating it
produces a DIFFERENT and equally correct file. What is checked, by
`tools/gen-golden-reference.py --interrupted --check`, is that this file still
carries the line shapes a rip interrupted right now produces -- which catches a
reworded line and claims nothing about the body.

Everything below this marker is the log byte for byte. It does not verify with
--verify-log while this header is attached, because the header is not part of
what the checksum covers; strip everything up to and including the next marker
line and it does.

Companion record: docs/sample-interrupted.diagnostics.json
=== END OF HEADER -- THE LOG ITSELF STARTS ON THE NEXT LINE ===
"""

SAMPLE_LOG = ROOT / "docs" / "sample-interrupted.log"
SAMPLE_JSON = ROOT / "docs" / "sample-interrupted.diagnostics.json"

# The three line shapes a consumer can ONLY see on an interrupted rip, and
# therefore the three the golden reference can never carry. Digits are
# wildcards; everything else is the text we undertake not to reword.
INTERRUPTED_SHAPES = (
    re.compile(r"^Rip completed:  no \(interrupted by SIGTERM, \d+ of \d+ tracks\)$",
               re.M),
    re.compile(r"^Stopping, ripping incomplete!$", re.M),
    re.compile(r"^Log FUN512: \S+$", re.M),
)


def generate_interrupted(binary):
    """A rip stopped by SIGTERM. Returns (log, json), or exits.

    NOT a golden reference and the file says so in its own header: where the
    signal lands is not reproducible, so how many frames were read, how many
    tracks completed and every timing differ between runs. It is a SAMPLE --
    one real artifact of a shape the canonical rip can never produce, so a
    consumer writing a parser for it has something to open instead of a
    paragraph describing it.

    What IS checked is in INTERRUPTED_SHAPES: the committed sample must contain
    each of those line shapes, and so must a rip run right now. That catches
    the thing worth catching -- a reworded line -- while not pretending the
    body is reproducible.
    """
    if os.name != "posix":
        sys.exit("the interrupted sample needs POSIX signals to produce")

    import signal as sig

    with tempfile.TemporaryDirectory() as td:
        work = Path(td)
        for f in FIX.glob("*.cue"):
            shutil.copy(f, work)
        shutil.copy(FIX / "cdda.bin", work / "pregap.bin")

        out = work / "o"
        stdout = work / "run.out"
        # -Z 200 -r 200 so the rip is long enough to interrupt without racing
        # its own completion. Same fixture and the same relative -D/-j as the
        # canonical rip, so the two artifacts differ in the interruption and
        # nothing else.
        argv = [str(binary), "-d", "pregap.cue", "-N", "-A", "-Q", "-s", "0",
                "-o", "flac", "-Z", "200", "-r", "200", "-G",
                "-F", "{track}", "-L", "sample", "-M", "sheet", "-P", "0",
                "-u", "platterpus/0.6.21", "-D", "o",
                "-j", "o/sample.diagnostics.json"]
        with stdout.open("wb") as fh:
            p = subprocess.Popen(argv, cwd=work, stdout=fh,
                                 stderr=subprocess.STDOUT)

        # Signal only once ripping is demonstrably under way: before the
        # handler is installed the signal is a default-disposition kill, which
        # would produce the truncated log this artifact exists to show we no
        # longer write.
        deadline = time.monotonic() + 30
        while time.monotonic() < deadline:
            if b"Ripping track" in stdout.read_bytes():
                break
            if p.poll() is not None:
                break
            time.sleep(0.05)
        else:
            p.kill(), p.wait()
            sys.exit("the sample rip never started")

        p.send_signal(sig.SIGTERM)
        try:
            p.wait(timeout=60)
        except subprocess.TimeoutExpired:
            p.kill(), p.wait()
            sys.exit("the sample rip did not stop on SIGTERM")

        log, js = out / "sample.log", out / "sample.diagnostics.json"
        if not log.exists() or not js.exists():
            sys.exit("the interrupted rip left no log or no diagnostics "
                     "record, which is the defect this artifact documents "
                     "being fixed:\n"
                     + stdout.read_bytes().decode(errors="replace")[-2000:])
        return log.read_text(), js.read_text()


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--binary", default=str(ROOT / "build" / "src" / "cyanrip"))
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed copy would change, "
                         "ignoring only wall-clock and invocation-path fields")
    ap.add_argument("--interrupted", action="store_true",
                    help="operate on docs/sample-interrupted.* instead")
    args = ap.parse_args()

    # Resolved before use: generate() runs the rip with cwd set to a staged
    # fixture directory, so a relative --binary would be looked up there and
    # fail with a bare FileNotFoundError that names the wrong problem.
    binary = Path(args.binary).resolve()
    if not binary.exists():
        sys.exit(f"{args.binary}: not built. Run ninja -C build first.")

    if args.interrupted:
        log, js = generate_interrupted(binary)
        banner = log.splitlines()[0]

        missing = [p.pattern for p in INTERRUPTED_SHAPES if not p.search(log)]
        if missing:
            sys.exit("a rip interrupted right now does not produce:\n  "
                     + "\n  ".join(missing))

        if args.check:
            if not SAMPLE_LOG.exists():
                sys.exit(f"{SAMPLE_LOG.relative_to(ROOT)} is missing")
            committed = SAMPLE_LOG.read_text()
            stale = [p.pattern for p in INTERRUPTED_SHAPES
                     if not p.search(committed)]
            if stale:
                sys.exit("the committed interrupted sample no longer matches "
                         "what this binary writes -- these shapes are absent "
                         "from it:\n  " + "\n  ".join(stale)
                         + "\nRegenerate with --interrupted.")
            # Deliberately NOT a body diff. Where the signal lands decides how
            # many frames were read and how many track blocks exist, so a
            # byte comparison would fail on every run for a reason that says
            # nothing about the format.
            print("interrupted sample carries the current line shapes")
            return 0

        if "-dirty" in banner:
            sys.exit(f"refusing to write a sample from a dirty build: {banner}\n"
                     "Commit, rebuild, and re-run.")

        # The header goes in the FILE, not only in a README, because the file
        # is what gets opened. Without it the obvious thing to do with an
        # artifact that sits beside a golden reference is to diff it, and that
        # would fail every time for a reason that says nothing.
        #
        # Prefixed with the log's own comment-free plain text: it is not a
        # cyanrip log any more once this is on it, and that is deliberate --
        # nothing should feed this to --verify-log and conclude the format is
        # broken. The unmodified log is reachable by removing the block, and
        # the block says so.
        SAMPLE_LOG.write_text(SAMPLE_HEADER + log)
        SAMPLE_JSON.write_text(js)
        print(f"wrote {SAMPLE_LOG.relative_to(ROOT)} and "
              f"{SAMPLE_JSON.relative_to(ROOT)}\n  {banner}")
        return 0

    log, js = generate(binary)

    banner = log.splitlines()[0]

    if args.check:
        if not OUT_LOG.exists():
            sys.exit("docs/golden-reference.log is missing")
        old = normalise(OUT_LOG.read_text())
        new = normalise(log)
        if old != new:
            import difflib
            d = list(difflib.unified_diff(old.splitlines(), new.splitlines(),
                                          "committed", "regenerated", lineterm=""))
            sys.exit("the golden reference is stale:\n" + "\n".join(d[:60]))
        print("golden reference is up to date")
        return 0

    # WRITE path only. A reference from a dirty tree names a commit that does
    # not describe it, which is the defect
    # sc_golden_reference_is_from_a_clean_build() exists to catch -- so refuse
    # here too, where it is cheap. NOT in --check: that mode normalises the
    # build tag by design, so it must stay runnable on a dirty working tree or
    # it could never be a `meson test`.
    if "-dirty" in banner:
        sys.exit(f"refusing to write a reference from a dirty build: {banner}\n"
                 "Commit, rebuild, and re-run.")

    OUT_LOG.write_text(log)
    OUT_JSON.write_text(js)
    print(f"wrote {OUT_LOG.relative_to(ROOT)} and "
          f"{OUT_JSON.relative_to(ROOT)}\n  {banner}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
