#!/usr/bin/env python3
#
# This file is part of cyanrip.
#
# cyanrip is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# cyanrip is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with cyanrip; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

"""Compile the handshake state into the binary, so a rip can report it.

The release rule lives in docs/handshake/ and is enforced at release time by
tools/release-gate.py. That is one step too late for the question a consumer
actually has, which is asked months afterwards while looking at a logfile:

    "was this rip produced by a pair of builds that had agreed with each other?"

Nothing in a log could answer that before. The version banner says which cyanrip
wrote it and nothing says whether that cyanrip was a released, mutually-verified
build or a mid-round working tree. Those are different provenance and an
archival record must not conflate them.

So the round state is compiled in from the same files the release gate reads,
and cyanrip prints it. A build from a tree with an open round says so, in every
logfile it writes, permanently.

Regenerated by meson whenever a round file changes, so it cannot go stale
against the documents it summarises -- a hand-maintained copy of this would be a
claim about the record rather than a derivation from it.
"""

import argparse
import importlib.util
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SPEC = importlib.util.spec_from_file_location(
    "release_gate", HERE / "release-gate.py")
rg = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(rg)


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _head_is(pin):
    """True when the tree being built is exactly `pin`.

    Compared as prefixes in whichever direction is shorter, because a lap names
    an abbreviated SHA and git answers with a full one. Any failure -- no pin
    declared, no git, a dirty tree -- returns False: a build whose provenance
    cannot be established is not a released build, and that is the direction
    that fails safe.
    """
    if not pin:
        return False
    try:
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                              capture_output=True, text=True,
                              check=True).stdout.strip()
        dirty = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT,
                               capture_output=True, text=True,
                               check=True).stdout.strip()
    except Exception:
        return False
    if dirty:
        return False
    return head.startswith(pin) or pin.startswith(head)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("output", nargs="?", help="header to write (default stdout)")
    args = ap.parse_args()

    rounds = rg.load_rounds()
    ok, _ = rg.check(rounds) if rounds else (False, ["no rounds"])
    latest = rounds[-1] if rounds else None

    if latest is None:
        # An empty record is not agreement. Say unknown rather than pretend.
        state = "unknown (no handshake record found)"
        released = 0
        peer = "unknown"
    else:
        lap = f" lap {latest.lap}" if latest.lap is not None else ""
        verdict = latest.verdict or "no verdict declared"
        if ok:
            state = f"round {latest.number}{lap} closed, verdict {verdict}"
            # A CLOSED ROUND IS NOT A RELEASED BUILD, and conflating them made
            # every log this tree writes into a false claim the moment round 8
            # closed.
            #
            # `ok` answers "is the record closed?" -- a question about
            # `HANDSHAKE-OUR-PIN`. HANDSHAKE_RELEASED renders a claim about THIS
            # BINARY. Those are different questions, and this collapsed them: at
            # the moment round 8 closed on ddf7ac3, the tree was 33 commits past
            # it carrying ten unreviewed defect fixes and one breaking schema
            # change, and every log it wrote would have dropped the
            # "-- NOT a released build" suffix and read as jointly verified.
            #
            # So the build must BE the approved pin. Fails closed on a tarball
            # or any tree where git cannot answer: unknown provenance is not a
            # release. No wording changes -- the tip keeps saying exactly what
            # it said before, which is the true thing.
            released = 1 if _head_is(latest.our_pin or latest.pin) else 0
        else:
            state = f"round {latest.number}{lap} OPEN, verdict {verdict}"
            released = 0
        peer = latest.app_version or latest.peer_version or "not recorded"

    body = f"""/* Generated by tools/gen-handshake-state.py. Do not edit.
 *
 * Derived from docs/handshake/, the same files tools/release-gate.py reads.
 * Regenerated by the build whenever one of them changes. */
#pragma once

#define HANDSHAKE_STATE     {c_string(state)}
#define HANDSHAKE_RELEASED  {released}
#define HANDSHAKE_PEER      {c_string(peer)}
"""

    if not args.output:
        sys.stdout.write(body)
        return 0

    # Written only when the content actually changes.
    #
    # This runs on every build (build_always_stale), because the header has to
    # notice a round file being *added*, not merely one it already knew about
    # changing. Neither a configure-time glob nor a depfile can do that: both
    # enumerate what existed last time, so a new lap file appears and the header
    # goes on describing the previous one. That happened here -- a binary
    # reported "lap 2" from a tree whose latest lap was 3, which is precisely the
    # staleness a generated header exists to prevent.
    #
    # Running every build is cheap; rewriting every build would not be, because
    # the timestamp alone would recompile everything that includes this. Hence
    # the comparison.
    out = pathlib.Path(args.output)
    if not out.exists() or out.read_text(encoding="utf-8") != body:
        out.write_text(body, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
